"""Add document_type to Media

Revision ID: 3563fc4ec0b2
Revises: a7501ca77ff1
Create Date: 2024-08-25 23:55:25.020788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3563fc4ec0b2'
down_revision = 'a7501ca77ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    # ### end Alembic commands ###
