"""Update schema to match current models

Revision ID: a7501ca77ff1
Revises: afeacb51e9bc
Create Date: 2024-08-25 14:26:45.825946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7501ca77ff1'
down_revision = 'afeacb51e9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_medication', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_of_refills', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_name', sa.String(length=255), nullable=False, server_default="document_name"))
        batch_op.add_column(sa.Column('document_url', sa.String(length=300), nullable=False, server_default="document_url"))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True, server_default="2024-08-25 14:26:45.825946"))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('url')

    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False, server_default="name"))
        batch_op.add_column(sa.Column('address', sa.String(length=70), nullable=False, server_default="address"))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='dob::date')
        batch_op.alter_column('subscription_start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('subscription_end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('quantity_of_refills')
        batch_op.drop_column('quantity')
        batch_op.drop_column('name_of_medication')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_medication', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity_of_refills', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('subscription_end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('subscription_start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('name')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('upload_date')
        batch_op.drop_column('document_url')
        batch_op.drop_column('document_name')

    op.drop_table('prescription')
    op.drop_table('note')
    # ### end Alembic commands ###
